name: ğŸš€ Deploy to Server Gulia

on:
  workflow_dispatch:  # ĞœĞ¾Ğ¶Ğ»Ğ¸Ğ²Ñ–ÑÑ‚ÑŒ Ğ·Ğ°Ğ¿ÑƒÑĞºÑƒ Ğ²Ñ€ÑƒÑ‡Ğ½Ñƒ Ğ»Ğ¸ÑˆĞµ Ñ‡ĞµÑ€ĞµĞ· GitHub UI

env:
  DEPLOY_PATH: "/home/TMP2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ” Hello World
      run: |
        echo "hello world"

